version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "commit_log"

  postgres1001:
    container_name: postgres_container1001
    image: postgres:14
    environment:
      POSTGRES_DB: "1001"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5431:5432"

  my-application1001:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres1001
    environment:
      DB_HOST: postgres1001
      PORT: 1001
      KAFKA_HOST: kafka:9092
    ports:
      - "1001:1001"

  postgres1002:
    container_name: postgres_container1002
    image: postgres:14
    environment:
      POSTGRES_DB: "1002"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5432:5432"

  my-application1002:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres1002
    environment:
      DB_HOST: postgres1002
      PORT: 1002
      KAFKA_HOST: kafka:9092
    ports:
      - "1002:1002"

  postgres1003:
    container_name: postgres_container1003
    image: postgres:14
    environment:
      POSTGRES_DB: "1003"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5433:5432"

  my-application1003:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres1003
    environment:
      DB_HOST: postgres1003
      PORT: 1003
      KAFKA_HOST: kafka:9092
    ports:
      - "1003:1003"

  postgres2001:
    container_name: postgres_container2001
    image: postgres:14
    environment:
      POSTGRES_DB: "2001"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5434:5432"

  my-application2001:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres2001
    environment:
      DB_HOST: postgres2001
      PORT: 2001
      KAFKA_HOST: kafka:9092
    ports:
      - "2001:2001"

  postgres2002:
    container_name: postgres_container2002
    image: postgres:14
    environment:
      POSTGRES_DB: "2002"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5435:5432"

  my-application2002:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres2002
    environment:
      DB_HOST: postgres2002
      PORT: 2002
      KAFKA_HOST: kafka:9092
    ports:
      - "2002:2002"

  postgres2003:
    container_name: postgres_container2003
    image: postgres:14
    environment:
      POSTGRES_DB: "2003"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5436:5432"

  my-application2003:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres2003
    environment:
      DB_HOST: postgres2003
      PORT: 2003
      KAFKA_HOST: kafka:9092
    ports:
      - "2003:2003"


  postgres3001:
    container_name: postgres_container3001
    image: postgres:14
    environment:
      POSTGRES_DB: "3001"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5437:5432"

  my-application3001:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres3001
    environment:
      DB_HOST: postgres3001
      PORT: 3001
      KAFKA_HOST: kafka:9092
    ports:
      - "3001:3001"

  postgres3002:
    container_name: postgres_container3002
    image: postgres:14
    environment:
      POSTGRES_DB: "3002"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5438:5432"

  my-application3002:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres3002
    environment:
      DB_HOST: postgres3002
      PORT: 3002
      KAFKA_HOST: kafka:9092
    ports:
      - "3002:3002"

  postgres3003:
    container_name: postgres_container3003
    image: postgres:14
    environment:
      POSTGRES_DB: "3003"
      POSTGRES_USER: "bestuser"
      POSTGRES_PASSWORD: "bestuser"
    #      PGDATA: /data/postgres # для чего это???
    ports:
      - "5439:5432"

  my-application3003:
    image: gift-certificates-api:1.0-SNAPSHOT
    depends_on:
      - kafka
      - postgres3003
    environment:
      DB_HOST: postgres3003
      PORT: 3003
      KAFKA_HOST: kafka:9092
    ports:
      - "3003:3003"


