spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #    hibernate:
  #      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/Node${PORT}?useSSL=true&serverTimezone=UTC
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver


server:
  port: ${PORT:9999}

  properties:
#    host: http://localhost
    ports:
      1: 9001
      2: 9002
      0: 9003



#    url: jdbc:postgresql://localhost:5432/taskX?useSSL=true&serverTimezone=UTC
#    username: bestuser
#    password: bestuser
#    driver-class-name: org.postgresql.Driver

#    node1:
#      jdbcUrl: jdbc:postgresql://localhost:5432/Node1?useSSL=true&serverTimezone=UTC
#      username: bestuser
#      password: bestuser
#      driver-class-name: org.postgresql.Driver
#    node2:
#      jdbcUrl: jdbc:postgresql://localhost:5432/Node2?useSSL=true&serverTimezone=UTC
#      username: bestuser
#      password: bestuser
#      driver-class-name: org.postgresql.Driver

