spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #    hibernate:
  #      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/${PORT}?useSSL=true&serverTimezone=UTC
    username: bestuser
    password: bestuser
    driver-class-name: org.postgresql.Driver
  cache:
    caffeine:
      spec: maximumSize=20,expireAfterAccess=1h

server:
  port: ${PORT:9999}

config:
  nodes:
    1:
      replicas:
        - port: 1001
        - port: 1002
        - port: 1003
    2:
      replicas:
        - port: 2001
        - port: 2002
        - port: 2003
    0:
      replicas:
        - port: 3001
        - port: 3002
        - port: 3003